# Desafio Calculadora inmobiliaria

In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np
import statsmodels.formula.api as smf
import pysal as ps
import re
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

E:\Miniconda3\envs\ds37\lib\site-packages\pysal\model\spvcm\abstracts.py:10: UserWarning: The `dill` module is required to use the sqlite backend fully.
  from .sqlite import head_to_sql, start_sql

In [2]:
df = pd.read_csv("properatti.csv")
df

,Unnamed: 0,operation,property_type,place_name,place_with_parent_names,country_name,state_name,geonames_id,lat-lon,lat,...,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses,properati_url,description,title,image_thumbnail
0,0,sell,PH,Mataderos,|Argentina|Capital Federal|Mataderos|,Argentina,Capital Federal,3430787.0,"-34.6618237,-58.5088387",-34.661824,...,40.0,1127.272727,1550.000000,NaN,NaN,NaN,http://www.properati.com.ar/15bo8_venta_ph_mat...,"2 AMBIENTES TIPO CASA PLANTA BAJA POR PASILLO,...",2 AMB TIPO CASA SIN EXPENSAS EN PB,https://thumbs4.properati.com/8/BluUYiHJLhgIIK...
1,1,sell,apartment,La Plata,|Argentina|Bs.As. G.B.A. Zona Sur|La Plata|,Argentina,Bs.As. G.B.A. Zona Sur,3432039.0,"-34.9038831,-57.9643295",-34.903883,...,NaN,NaN,NaN,NaN,NaN,NaN,http://www.properati.com.ar/15bob_venta_depart...,Venta de departamento en décimo piso al frente...,VENTA Depto 2 dorm. a estrenar 7 e/ 36 y 37 ...,https://thumbs4.properati.com/7/ikpVBu2ztHA7jv...
2,2,sell,apartment,Mataderos,|Argentina|Capital Federal|Mataderos|,Argentina,Capital Federal,3430787.0,"-34.6522615,-58.5229825",-34.652262,...,55.0,1309.090909,1309.090909,NaN,NaN,NaN,http://www.properati.com.ar/15bod_venta_depart...,2 AMBIENTES 3ER PISO LATERAL LIVING COMEDOR AM...,2 AMB 3ER PISO CON ASCENSOR APTO CREDITO,https://thumbs4.properati.com/5/SXKr34F_IwG3W_...
3,3,sell,PH,Liniers,|Argentina|Capital Federal|Liniers|,Argentina,Capital Federal,3431333.0,"-34.6477969,-58.5164244",-34.647797,...,NaN,NaN,NaN,NaN,NaN,NaN,http://www.properati.com.ar/15boh_venta_ph_lin...,PH 3 ambientes con patio. Hay 3 deptos en lote...,PH 3 amb. cfte. reciclado,https://thumbs4.properati.com/3/DgIfX-85Mog5SP...
4,4,sell,apartment,Centro,|Argentina|Buenos Aires Costa Atlántica|Mar de...,Argentina,Buenos Aires Costa Atlántica,3435548.0,"-38.0026256,-57.5494468",-38.002626,...,35.0,1828.571429,1828.571429,NaN,NaN,NaN,http://www.properati.com.ar/15bok_venta_depart...,DEPARTAMENTO CON FANTÁSTICA ILUMINACIÓN NATURA...,DEPTO 2 AMB AL CONTRAFRENTE ZONA CENTRO/PLAZA ...,https://thumbs4.properati.com/5/xrRqlNcSI_vs-f...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121215,121215,sell,apartment,Belgrano,|Argentina|Capital Federal|Belgrano|,Argentina,Capital Federal,3436077.0,NaN,NaN,...,93.0,7699.115044,9354.838710,NaN,NaN,10000.0,http://www.properati.com.ar/1cja2_venta_depart...,TORRE FORUM ALCORTA - MÁXIMA CATEGORÍA.Impecab...,Torre Forum Alcorta- Impecable 3 ambientes,https://thumbs4.properati.com/1/bjms0KnaAnlNoQ...
121216,121216,sell,house,Beccar,|Argentina|Bs.As. G.B.A. Zona Norte|San Isidro...,Argentina,Bs.As. G.B.A. Zona Norte,3436080.0,NaN,NaN,...,360.0,1383.333333,1383.333333,NaN,NaN,NaN,http://www.properati.com.ar/1cja6_venta_casa_b...,Excelente e impecable casa en Venta en Las Lom...,Ruca Inmuebles | Venta | Lomas de San Isidro |...,https://thumbs4.properati.com/2/PCc3WuQDjpNZc4...
121217,121217,sell,apartment,Villa Urquiza,|Argentina|Capital Federal|Villa Urquiza|,Argentina,Capital Federal,3433775.0,"-34.5706388726,-58.4755963355",-34.570639,...,39.0,2858.695652,3371.794872,NaN,NaN,NaN,http://www.properati.com.ar/1cja7_venta_depart...,VENTA DEPARTAMENTO AMBIENTE DIVISIBLE A ESTREN...,VENTA DEPARTAMENTO AMBIENTE DIVISIBLE A ESTREN...,https://thumbs4.properati.com/9/YAe_-2gRVykADP...
121218,121218,sell,apartment,Plaza Colón,|Argentina|Buenos Aires Costa Atlántica|Mar de...,Argentina,Buenos Aires Costa Atlántica,NaN,NaN,NaN,...,48.0,1997.916667,1997.916667,NaN,NaN,NaN,http://www.properati.com.ar/1cja8_venta_depart...,"2 Amb al contrafrente, luminoso. El departame...",2 amb. C/ dep. de servicio al contrafrente| Re...,https://thumbs4.properati.com/8/Q12PTvU6BQJ0ib...
121219,121219,sell,apartment,Capital Federal,|Argentina|Capital Federal|,Argentina,Capital Federal,3433955.0,NaN,NaN,...,77.0,1675.324675,1675.324675,NaN,NaN,3500.0,http://www.properati.com.ar/1cjaa_venta_depart...,Departamento de 77 m2 apto profesional. Edific...,Departamento apto profesional en el Centro,https://thumbs4.properati.com/8/mNEsnQWqB7joBF...

In [4]:
df.loc[~(df.rooms.isnull())].shape

(47390, 26)

In [5]:
place_split = df.place_with_parent_names.str.split('|', expand=True).rename({1:'pais', 2:'provincia',
                                                               3:'partido', 4:'localidad',
                                                               5:'barrio', 6:'zona'}, axis=1).drop(0, axis=1)

place_split.sample(15)

,pais,provincia,partido,localidad,barrio,zona
6569,Argentina,Bs.As. G.B.A. Zona Oeste,Morón,,None,None
50406,Argentina,Bs.As. G.B.A. Zona Sur,,None,None,None
51476,Argentina,Capital Federal,Villa del Parque,,None,None
56642,Argentina,Capital Federal,Villa Crespo,,None,None
17035,Argentina,Buenos Aires Costa Atlántica,Mar del Plata,,None,None
29627,Argentina,Bs.As. G.B.A. Zona Norte,San Fernando,Victoria,,None
119927,Argentina,Capital Federal,Villa Devoto,,None,None
3667,Argentina,Bs.As. G.B.A. Zona Oeste,Morón,,None,None
14721,Argentina,Río Negro,San Carlos de Bariloche,San Carlos de Bariloche,,None
1923,Argentina,Capital Federal,Boca,,None,None
11465,Argentina,Capital Federal,Villa Ortuzar,,None,None
30732,Argentina,Bs.As. G.B.A. Zona Norte,Tigre,,None,None
75491,Argentina,Buenos Aires Interior,Luján,Luján,,None
69744,Argentina,Córdoba,Córdoba,,None,None
89721,Argentina,Capital Federal,San Telmo,,None,None

Este código hace exactamente lo mismo y sería la forma más limpia de hacerlo
```python
df.place_with_parent_names.str.split('|', expand=True).rename({1:'pais', 2:'provincia',
                                                               3:'partido', 4:'localidad',
                                                               5:'barrio', 6:'zona'}, axis=1).drop(0, axis=1)
#Alternativa
place_split = df.place_with_parent_names.apply(lambda x: x.split('|')).apply(pd.Series)\
                            .rename({1:'pais', 2:'provincia', 3:'partido', 4:'localidad',5:'barrio', 6:'zona'}, axis=1)\
                            .drop(0, axis=1)
```

In [6]:
place_split.sample(15)

,pais,provincia,partido,localidad,barrio,zona
106233,Argentina,Santa Fe,Rosario,,None,None
39902,Argentina,Buenos Aires Costa Atlántica,Las Gaviotas,,None,None
45049,Argentina,Bs.As. G.B.A. Zona Norte,San Isidro,Acassuso,,None
14846,Argentina,Bs.As. G.B.A. Zona Norte,Pilar,Boca Ratón,,None
87406,Argentina,Bs.As. G.B.A. Zona Norte,Pilar,,None,None
35701,Argentina,Bs.As. G.B.A. Zona Oeste,La Matanza,San Justo,,None
17104,Argentina,Capital Federal,Caballito,,None,None
29077,Argentina,Buenos Aires Costa Atlántica,Mar del Plata,,None,None
6875,Argentina,Bs.As. G.B.A. Zona Oeste,Morón,Haedo,,None
55090,Argentina,Santa Fe,Rosario,,None,None
117568,Argentina,Bs.As. G.B.A. Zona Sur,Lomas de Zamora,,None,None
118277,Argentina,Córdoba,Córdoba,,None,None
29247,Argentina,Bs.As. G.B.A. Zona Oeste,Tres de Febrero,Ciudadela,,None
492,Argentina,Bs.As. G.B.A. Zona Norte,Malvinas Argentinas,Villa de Mayo,,None
46743,Argentina,Córdoba,Villa Carlos Paz,,None,None

In [7]:
pattern = []
df.head(10).description[0]

'2 AMBIENTES TIPO CASA PLANTA BAJA POR PASILLO, REFACCIONADO A NUEVO, PATIO GRANDE, CON LAVADERO, LIVING COMEDOR CON COCINA INTEGRADA, ARTEFACTO DE COCINA, ALACENA, BAÑO COMPLETO, Y DORMITORIO. TODO EN EXCELENTE ESTADO, PARA HABITAR.NO ES APTO CREDITO Aviso publicado por Pixel Inmobiliario (Servicio de Páginas Web para Inmobiliarias).'

In [8]:
df.loc[df['title'].str.contains(r'amb'), 'title'].sample().to_csv()

E:\Miniconda3\envs\ds37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.

'84157,Monoambiente en Flores departamentos de pozo\r\n'

In [29]:
pattern_usd = r'[u$s dolares]?((?!\()\d{1,3}[,.]\d{1,3}[,.]?\d{3}?(?!\)))|((?!\()\d{1,3}[,.]\d{3}(?!\)))|((?!\()\d{5,}(?!\)))'
pat_tag_usd = r'(usd|u\$s|us\$|dolares|dólares|us)'
pat_tag_ars = r''

In [31]:
pat_ambientes = r'\b(\d{1,2})\s*amb'
pat_dormitorios = r'\b(\d{1,2})\s*dor'

In [11]:
df['ambientes'] = df.title.str.extract(pat_amibentes, re.IGNORECASE, expand=True)
df['dormitorios'] = df.title.str.extract(pat_dormitorios, re.IGNORECASE, expand=True)

In [12]:
df.loc[~(df.ambientes.isnull())].filter(['description', 'ambientes'])

                                              description ambientes
0       2 AMBIENTES TIPO CASA PLANTA BAJA POR PASILLO,...         2
2       2 AMBIENTES 3ER PISO LATERAL LIVING COMEDOR AM...         2
3       PH 3 ambientes con patio. Hay 3 deptos en lote...         3
4       DEPARTAMENTO CON FANTÁSTICA ILUMINACIÓN NATURA...         2
12      EXCELENTE DEPARTAMENTO 2 AMBIENTES CONTRAFRENT...         2
...                                                   ...       ...
121131  Excelente semipiso al frente de 4 ambientes. E...         3
121138  VENTA CON RENTA DEPARTAMENTO DE 2 AMBIENTES A ...         2
121153  EXCELENTE DEPARTAMENTO CON TERRAZA PROPIA Y PA...         3
121215  TORRE FORUM ALCORTA - MÁXIMA CATEGORÍA.Impecab...         3
121218  2 Amb al contrafrente,  luminoso. El departame...         2

[21799 rows x 2 columns]

In [13]:
a = df.filter(['ambientes', 'dormitorios', 'rooms']).loc[~(df.rooms.isnull()) &\
                                                         ~(df.ambientes.isnull())].ambientes.astype(np.float64)\
    == df.filter(['ambientes', 'dormitorios', 'rooms']).loc[~(df.rooms.isnull()) & ~(df.ambientes.isnull())].rooms

In [14]:
a.count()/len(a)

1.0

El resultado anterior indica que rooms y ambientes es lo mismo, por lo que podemos rellenar los `NaN` de *'rooms'* con *'ambientes'*

In [15]:
df.loc[~(df.dormitorios.isnull())].filter(['description', 'dormitorios'])

                                              description dormitorios
1       Venta de departamento en décimo piso al frente...           2
9       MEDNOZA AL 7600A UNA CUADRA DE CALLE MENDOZAWH...           2
34      Amplio PH de 5 dormitorios, ubicado a 3 cuadra...           5
73      SE VENDE CASA EN EL MICROCENTRO DE 150 mts2 CO...           2
83      IDEAL INVERSORES o ESTUDIANTES APTA CREDITO An...           2
...                                                   ...         ...
120331  Gran departamento en venta de 3 dormitoriosDep...           3
120962  Hermosa Casa sobre gran lote en esquina muy lu...           4
120966  HDH Propiedades presenta  a la venta casa apta...           3
121101  Excelente casa de dos plantas a entrenar en Sa...           3
121144  OLSEN PROPIEDADES TIENE EL AGRADO DE PRESENTAR...           3

[7764 rows x 2 columns]

In [16]:
df.rooms.fillna(df.ambientes, inplace=True)
df.filter(['rooms', 'ambientes', 'dormitorios']).loc[~(df.rooms.isnull())]

       rooms ambientes dormitorios
0          2         2         NaN
2          2         2         NaN
3          3         3         NaN
4          2         2         NaN
12         2         2         NaN
...      ...       ...         ...
121131     3         3         NaN
121138     2         2         NaN
121153     3         3         NaN
121215     3         3         NaN
121218     2         2         NaN

[56060 rows x 3 columns]

In [18]:
df['re_usd'] = df.title.str.extract(pat_tag_usd, re.IGNORECASE)

In [19]:
df.columns

Index(['Unnamed: 0', 'operation', 'property_type', 'place_name',
       'place_with_parent_names', 'country_name', 'state_name', 'geonames_id',
       'lat-lon', 'lat', 'lon', 'price', 'currency',
       'price_aprox_local_currency', 'price_aprox_usd', 'surface_total_in_m2',
       'surface_covered_in_m2', 'price_usd_per_m2', 'price_per_m2', 'floor',
       'rooms', 'expenses', 'properati_url', 'description', 'title',
       'image_thumbnail', 'ambientes', 'dormitorios', 're_usd'],
      dtype='object')

In [20]:
df.loc[~(df.re_usd.isnull())&(df.price.isnull())].filter(['re_usd']).values

array([['US'],
       ['US'],
       ['US'],
       ['US'],
       ['US'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['Us'],
       ['US'],
       ['us'],
       ['US'],
       ['us'],
       ['US'],
       ['US'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['US'],
       ['US'],
       ['US'],
       ['us'],
       ['US'],
       ['US'],
       ['US'],
       ['us'],
       ['US'],
       ['US'],
       ['us'],
       ['us'],
       ['US'],
       ['us'],
       ['US'],
       ['us'],
       ['US'],
       ['US'],
       ['US'],
       ['US'],
       ['us'],
       ['US'],
       ['US'],
       ['US'],
       ['US'],
       ['US'],
       ['us'],
       ['us'],
       ['US'],
       ['us'],
       ['US'],
       ['us'],
       ['US'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['US'],
       ['U$S'],
       ['us'],
       ['US'],
       ['US'],
       ['US'],
       ['us'],
       ['us'],
       ['US'],
       ['US'],
       ['us'],
       ['us'],
       ['US'],
       ['US'],
       ['US'],
       ['U$S'],
       ['us'],
       ['us'],
       ['US'],
       ['us'],
       ['US'],
       ['us'],
       ['US'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['US'],
       ['US'],
       ['US'],
       ['US'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['US'],
       ['us'],
       ['US'],
       ['US'],
       ['US'],
       ['US'],
       ['us'],
       ['us'],
       ['U$S'],
       ['us'],
       ['us'],
       ['US'],
       ['US'],
       ['US'],
       ['us'],
       ['us'],
       ['US'],
       ['us'],
       ['us'],
       ['us'],
       ['US'],
       ['US'],
       ['us'],
       ['us'],
       ['US'],
       ['US'],
       ['us'],
       ['US'],
       ['us'],
       ['us'],
       ['us'],
       ['USD'],
       ['us'],
       ['us'],
       ['U$S'],
       ['U$S'],
       ['U$S'],
       ['U$S'],
       ['Us'],
       ['us'],
       ['us'],
       ['US'],
       ['US'],
       ['us'],
       ['us'],
       ['US'],
       ['US'],
       ['us'],
       ['US'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['US'],
       ['US'],
       ['us'],
       ['us'],
       ['US'],
       ['US'],
       ['US'],
       ['us'],
       ['u$s'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['US'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['US'],
       ['US'],
       ['us'],
       ['us'],
       ['us'],
       ['US'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['US'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['U$S'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['US'],
       ['US'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['US'],
       ['US'],
       ['US'],
       ['us'],
       ['US'],
       ['us'],
       ['us'],
       ['US'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['US'],
       ['us'],
       ['US'],
       ['u$s'],
       ['us'],
       ['us'],
       ['us'],
       ['US'],
       ['us'],
       ['US'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['US'],
       ['us'],
       ['us'],
       ['us'],
       ['US'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['US'],
       ['us'],
       ['US'],
       ['US'],
       ['us'],
       ['US'],
       ['US'],
       ['US'],
       ['US'],
       ['us'],
       ['us'],
       ['US'],
       ['us'],
       ['us'],
       ['US'],
       ['US'],
       ['US'],
       ['us'],
       ['us']], dtype=object)

In [21]:
df.iloc[8]['title']

'JOSE HERNANDEZ   1400 DOS AMBIENTES ESTRENAR , CATEGORIA , VENTA'

In [35]:
df['amb_description'] = df.description.str.extract(pat_ambientes, re.IGNORECASE, expand=True)

(37438,)

In [44]:
df.rooms.fillna(df.amb_description, inplace=True)

In [46]:
df.loc[~(df.rooms.isnull())].rooms.shape

(69047,)